[package]
name = "meilisearch-http"
description = "MeiliSearch HTTP server"
version = "0.15.0"
license = "MIT"
authors = [
    "Quentin de Quelen <quentin@dequelen.me>",
    "Clément Renault <clement@meilisearch.com>",
]
edition = "2018"

[[bin]]
name = "meilisearch"
path = "src/main.rs"

[features]
default = ["sentry"]

[dependencies]
actix-cors = "0.4.1"
actix-http = "2"
actix-rt = "1"
actix-service = "1.0.6"
actix-web = { version = "3.1.0", features = ["rustls"] }
bytes = "0.5.4"
chrono = { version = "0.4.19", features = ["serde"] }
crossbeam-channel = "0.5.0"
env_logger = "0.7.1"
flate2 = "1.0.18"
futures = "0.3.6"
http = "0.2.1"
indexmap = { version = "1.3.2", features = ["serde-1"] }
log = "0.4.8"
main_error = "0.1.0"
meilisearch-core = { path = "../meilisearch-core", version = "0.15.0" }
meilisearch-error = { path = "../meilisearch-error", version = "0.15.0" }
meilisearch-schema = { path = "../meilisearch-schema", version = "0.15.0" }
meilisearch-tokenizer = {path = "../meilisearch-tokenizer", version = "0.15.0"}
mime = "0.3.16"
once_cell = "1.4.1"
rand = "0.7.3"
regex = "1.4.1"
rustls = "0.18"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = { version = "1.0.59", features = ["preserve_order"] }
serde_qs = "0.7.0"
sha2 = "0.9.1"
siphasher = "0.3.2"
slice-group-by = "0.2.6"
structopt = "0.3.20"
tar = "0.4.29"
tempfile = "3.1.0"
tokio = { version = "1.2.0", features = ["macros"] }
ureq = { version = "1.5.1", features = ["tls"], default-features = false }
walkdir = "2.3.1"
whoami = "0.9.0"

[dependencies.sentry]
version = "0.18.1"
default-features = false
features = [
    "with_client_implementation",
    "with_panic",
    "with_failure",
    "with_device_info",
    "with_rust_info",
    "with_reqwest_transport",
    "with_rustls",
    "with_env_logger"
]
optional = true

[dev-dependencies]
serde_url_params = "0.2.0"
tempdir = "0.3.7"
tokio = { version = "1.2.0", features = ["macros", "time"] }

[dev-dependencies.assert-json-diff]
git = "https://github.com/qdequele/assert-json-diff"
branch = "master"

[build-dependencies]
vergen = "3.1.0"

[target.'cfg(unix)'.dependencies]
jemallocator = "0.3.2"
